### ISSUE TITLE
CheckConstraint.check is marked as deprecated in Django 5.1

### ISSUE THREAD

**Issue by decadecity** [RealOrangeOne/django-tasks#100]
I've upgraded the project I'm using to trial tasks to Django 5.1 and I am now receiving the following deprecation warning:

`django_tasks/backends/database/models.py:103: RemovedInDjango60Warning: CheckConstraint.check is deprecated in favor of '.condition'.`

Per the [Django 5.1 release notes](https://docs.djangoproject.com/en/5.1/releases/5.1/#id2):

> * The check keyword argument of CheckConstraint is deprecated in favor of condition.

This is also reflected in the [documentation for CheckConstraint](https://docs.djangoproject.com/en/5.1/ref/models/constraints/#checkconstraint)

## Environment

 * Python 3.11.4
 * Django 5.1.0
 * django-tasks 0.3.0

**Comment by RealOrangeOne** [comment]
It's deprecated, but `condition` isn't supported in 4.2.

I'm open to adding a Django version check, and passing either `condition` or `check` as needed, so long as it's not much additional complexity.
