### ISSUE TITLE
Completion information

### ISSUE THREAD

**Issue by RealOrangeOne** [RealOrangeOne/django-tasks#31]
Currently, it's not possible to determine when a task completed, nor when it was scheduled. This makes it more difficult to measure how long tasks have been in the queue, which is helpful when analysing queue depth (a la #12).

2 new fields should be added:

- `enqueued_at`: When the task was enqueued
- `finished_at`: When the task finished running (whether it succeeded or not)

**Comment by dennisstritzke** [comment]
I am attending the DjangoCon sprint and working on this.
