### ISSUE TITLE
Allow `ImmediateBackend` to throw its errors

### ISSUE THREAD

**Issue by RealOrangeOne** [RealOrangeOne/django-tasks#50]
If a task fails using the `ImmediateBackend`, this exception is currently swallowed and isn't accessible anywhere. This should be rectified by adding a `logger.exception` call to ensure the error is seen, and captured by error monitoring. This matches the behaviour of the database backend.

**Comment by RealOrangeOne** [comment]
Currently, `Exception` is caught. This may need extending to `BaseException` with cut-outs for `KeyboardInterrupt`

**Comment by jribbens** [comment]
> Currently, `Exception` is caught. This may need extending to `BaseException` with cut-outs for `KeyboardInterrupt`

That would mean it catches `GeneratorExit` and `SystemExit`, why would you want that?

**Comment by RealOrangeOne** [comment]
If a task throws `SystemExit` for whatever reason, I don't want the process to terminate. It should be caught as if the task failed, and control continue. 

`KeyboardInterrupt` only needs cutting out as a quality of life fix. There might be others like it, but I don't think `SystemExit` is one of them.

**Comment by jribbens** [comment]
Catching and squashing `SystemExit` is a bold strategy ;-) But if you really want to do that then explicitly catching `Exception` and `SystemExit` would seem the appropriate way.
