### ISSUE TITLE
Management command for cleaning up task results

### ISSUE THREAD

**Issue by GitRon** [RealOrangeOne/django-tasks#76]
Hi @RealOrangeOne 

first of all: Great work what you are doing here ❤️ 

I have a suggestion: Similar to the `clearsessions` command to clean up expired sessions, I think it would be a great (and simple) addition to have a command to clean up "done" result backends.

Unlike sessions, task results are not just "active" or "expired" since a "done" task can be either "finished" or "failed". In addition, you might want to keep finished task results around for a while for debugging purposes.

Therefore, it might be worth adding two parameters. The first determines what we want to ger rid of (e.g. only "finished" tasks), the second could set a timedelta after which task results might be removed, e.g. older than 1 week.

I'd be happy to hear your thoughts on my idea.

Best from Cologne  
Ronny

**Comment by RealOrangeOne** [comment]
I agree this is something that's absolutely needed, although now something I've got around to yet.

There's an issue covering this already (#16), and a related PR (#60), but I'm not happy with the PR quite yet, and might merge it with the `db_worker` command to only need a single process to run. More thought needed!
