### ISSUE TITLE
Make it easy to stop the database worker by sending it SIGQUIT or repeated SIGINT

### ISSUE THREAD

**Issue by mgax** [RealOrangeOne/django-tasks#84]
When trying things out locally, it's helpful to be able to kill a worker that's blocked on a task, without having to either run `kill -9 {pid}` in a separate shell, or killing the terminal window entirely. Many tools will treat a single `SIGINT` as "please exit gracefully" and a follow-on `SIGINT` as "please exit and ignore the consequences". Other programs respond to `SIGQUIT` (which can often be triggered by pressing `ctrl-\`).

---
Happy to write up a PR for this.

**Comment by RealOrangeOne** [comment]
Big fan of this idea. Distinguishing between "terminate after the current task" and "terminate now" would be incredibly useful. I think `ctrl-c` needs to be the latter during development, and the former in production, which might be counter-intuitive.

PR more than welcome!

**Comment by mgax** [comment]
> I think `ctrl-c` needs to be the latter during development, and the former in production, which might be counter-intuitive.

For development, pressing `ctrl-c` twice can do "terminate now". This is what `docker compose up` (without `-d`) does:

```
% docker compose up app
[+] Running 1/1
 ✔ Container demo-app-1     Created                     0.0s 
Attaching to web-1
^CGracefully stopping... (press Ctrl+C again to force)
[+] Stopping 1/1
 ✔ Container demo-app-1  Stopped                       1.5s 
canceled
```
