### ISSUE TITLE
Mention configuring logging in the documentation

### ISSUE THREAD

**Issue by bmihelac** [RealOrangeOne/django-tasks#90]
"Default Django logging would not emit any messages, even with python manage.py db_worker -v2.

I believe that django_tasks should be added to the loggers of the LOGGING settings."

Example:

```
    "loggers": {
        # Configure logging for django_tasks
        "django_tasks": {
            "handlers": ["console", "mail_admins"],
            "level": "INFO",
        },
```

I can create pull request to add a section in [README.md](https://github.com/RealOrangeOne/django-tasks/blob/master/README.md)

**Comment by RealOrangeOne** [comment]
This sounds more like it might be a bug to me - there's manual code to handle setting the log level to something expected:

https://github.com/RealOrangeOne/django-tasks/blob/39ceb97c672109daab94ef1ca8b95905932554f4/django_tasks/backends/database/management/commands/db_worker.py#L202-L215

**Comment by bmihelac** [comment]
Yes, I saw that code, and it works as expected, once django_tasks is in the LOGGING settings for Django.

Maybe I am missing something, but I have always needed to update the LOGGING settings for Django to log third-party apps.

 [django-rq](https://github.com/rq/django-rq?tab=readme-ov-file#configuring-logging) also mention this, for example.

**Comment by RealOrangeOne** [comment]
There's no logging setup in the test suite, and it definitely works there. I'll see if I can work out what's going on.

**Comment by bmihelac** [comment]
Hm, I just running db_worker from this project and indeed it does print. I'll try with fresh django app.

```bash
./manage.py db_worker -v2
Starting worker for queues=default
^CReceived Interrupt - shutting down gracefully... (press Ctrl+C again to force)
```

**Comment by bmihelac** [comment]
I cannot reproduce this on the fresh setup. Sorry for the noise.

Just for your information, the default setup does not `mail admins` on exceptions inside tasks, so adding logging configuration information might still be useful.
