### ISSUE TITLE
Task Results admin ordering

### ISSUE THREAD

**Issue by bmihelac** [RealOrangeOne/django-tasks#93]
Task Results admin uses [default](https://github.com/RealOrangeOne/django-tasks/blob/master/django_tasks/backends/database/models.py#L99) ordering `[F("priority").desc(), F("run_after").desc(nulls_last=True)]` which is not very useful when reviewing tasks.

If there are no specific reasons not to, I propose that records in admin are sorted by Enqueued at descending (`-enqueued_at`) so last added tasks are shown first.

**Comment by RealOrangeOne** [comment]
This sounds sensible to me!

**Comment by bmihelac** [comment]
Great - I'll prepare PR.
