### ISSUE TITLE
Mark model fields for translation

### ISSUE THREAD

**Issue by bmihelac** [RealOrangeOne/django-tasks#94]
It would be nice to mark  `DBTaskResult` model fields and status labels for translation so they can be translated if needed.

Please close this issue if it is too early for translations.

**Comment by RealOrangeOne** [comment]
What do you imagine would be translated?

**Comment by bmihelac** [comment]
I guess everything that is visible in admin, that is:

* DBTaskResult model verbose_name, verbose_name_plural
* all DBTaskResult fields verbose name
* ResultStatus labels

**Comment by RealOrangeOne** [comment]
Good point - I'd definitely welcome a PR to improve this!

**Comment by bmihelac** [comment]
Great - I'll prepare PR.
